version: '3'

services:
  dotnetservice:
    container_name: dotnetservicecontainer
    build: .    
    ports:
      - "3000:80"
    depends_on:
      - db    
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_database/mysql-data:/var/lib/mysql:rw
volumes:
  mysql-data:
